# Generated by Django 3.2 on 2021-08-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='total_item',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='stock_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='used_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
