# Generated by Django 3.2 on 2021-08-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='researcharticle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
