# Generated by Django 3.2 on 2021-08-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psm', '0002_auto_20210820_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='image',
        ),
        migrations.RemoveField(
            model_name='researcharticle',
            name='image',
        ),
        migrations.AddField(
            model_name='notice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='researcharticle',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='notice',
            name='body',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='researcharticle',
            name='body',
            field=models.CharField(max_length=2000),
        ),
    ]
