# Generated by Django 3.2 on 2021-08-09 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psm', '0002_auto_20210809_0645'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.IntegerField(blank=True, null=True)),
                ('used_quantity', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_stores', to='psm.district')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_stores', to='psm.item')),
            ],
        ),
    ]
