# Generated by Django 3.2 on 2021-08-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psm', '0003_districtstore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Covid -19'), (2, 'Dengue/Chikungunya'), (3, 'Cholera')], null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
