# Generated by Django 3.2 on 2021-08-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psm', '0004_auto_20210813_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
