# Generated by Django 3.2 on 2021-08-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psm', '0005_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Covid Medical Item'), (2, 'Covid Safety Item'), (3, 'Dengue/Chikungunya'), (4, 'Cholera')], null=True),
        ),
    ]
