# Generated by Django 3.2 on 2021-08-16 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psm', '0006_alter_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjacentDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjacent_district', models.ManyToManyField(related_name='districts', to='psm.District')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjacent_districts', to='psm.district')),
            ],
        ),
    ]
