# Generated by Django 3.2 on 2021-08-16 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psm', '0007_adjacentdistrict'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeighborDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbor_districts', to='psm.district')),
                ('neighbor_district', models.ManyToManyField(related_name='districts', to='psm.District')),
            ],
        ),
        migrations.DeleteModel(
            name='AdjacentDistrict',
        ),
    ]
