# Generated by Django 3.2 on 2021-08-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psm', '0008_auto_20210816_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
