# Generated by Django 3.2 on 2021-08-17 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psm', '0009_researcharticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_body', models.IntegerField(choices=[(1, 'National'), (2, 'NeighborDistrict')], default=1)),
                ('quantity', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved')], default=1)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_items', to='psm.district')),
                ('request_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_items', to='psm.district')),
            ],
        ),
    ]
