# Generated by Django 3.2 on 2021-08-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psm', '0010_requesteditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesteditem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='requesteditem',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
