# Generated by Django 3.2 on 2021-08-17 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psm', '0011_auto_20210817_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesteditem',
            name='district',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_items', to='psm.district'),
        ),
        migrations.AlterField(
            model_name='requesteditem',
            name='request_body',
            field=models.IntegerField(blank=True, choices=[(1, 'National'), (2, 'NeighborDistrict')], default=1),
        ),
        migrations.AlterField(
            model_name='requesteditem',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Approved')], default=1),
        ),
    ]
