# Generated by Django 3.2 on 2021-08-17 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psm', '0013_auto_20210817_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesteditem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_items', to='psm.item'),
        ),
    ]
